Functions get and clean for continuous water temperature data. Also r…
Delta-Stewardship-Council/swg-21-connectivity pull request #43
Opened 2021-12-01 20:49 UTC by catarfish

…aw and cleaned data files, as well as station file.

2021-12-01 23:26 UTC, ryanpeek requested changes
This looks good. I'd recommend commenting out or removing the mapview lines in the `f_clean_watertemp.R` script. Generally the visualization stuff can be done outside of the function, because it can bog things down. Let me know if you want me to merge as is (and we can worry about it later), or if you want me to wait to merge until after you push up that small edit.

2021-12-01 23:27 UTC, ryanpeek commented on scripts/functions/f_clean_watertemp.R
> +  mapview::mapView(stations_sf)
suggest removing this bit for the function.

2021-12-01 23:31 UTC, ryanpeek commented on scripts/functions/f_clean_watertemp.R
> +  stations_filtered_sf <- stations_filtered %>%
same here, I'd remove anything that isn't used and returned in the `return` call...so `stations_filtered_sf` can get commented out or deleted too.

2021-12-02 16:37 UTC, catarfish commented
Hi Ryan,

Commented them out and pushed, so I think you can go ahead and merge now.

2021-12-02 16:54 UTC, merged