Water ops
Delta-Stewardship-Council/swg-21-connectivity pull request #61
Opened 2022-02-17 19:16 UTC by goertler

script and plots to investigate influence of water ops for next meeting

2022-02-17 20:37 UTC, ryanpeek requested changes
@goertler I would recommend not pushing the tiff's up (in fact, I would ignore them completely using a line in your .gitignore "figures/*.tiff". They are very large (+20 MB each), and so pushing and pulling them will take a long time, and will happen every time they need updating. Better to save a version as a jpg or png in the interim, and when needed you can generate the tiff for production/manuscript locally (and not push it up).

2022-02-17 20:38 UTC, ryanpeek commented on investigate_water_ops.R
> +tiff(filename = "figures/sac_vs_yolo.tiff", width = 10, height = 8, units = "in", res = 300)
use png or pdf here... much smaller file sizes and still good resolution

2022-02-17 20:44 UTC, ryanpeek commented on investigate_water_ops.R
> +
Need a read.csv or load data of some sort...can't duplicate this code without the dataset?

2022-02-17 20:48 UTC, ryanpeek commented
@goertler @catarfish I made a few minor changes to the code, and removed the tiffs from this pull request. Make sure to pull to your branch in your repo first (to incorporate these edits), then you can rerun and fix the bit at the beginning with the data, regenerate the plots as pngs, and then commit and push, we can merge things in pretty quickly! Let me know if you have questions.

2022-02-22 22:26 UTC, merged

2022-02-22 22:27 UTC, goertler commented
Thanks Ryan, done and done (I ended up changing the inundation data file a bit so that this R script can just pull from one source).